name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK with Buildozer (verbose)
        uses: digreatbrian/buildozer-action@v2
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          buildozer-cmd: buildozer -v android debug
